In [7]:
#variable and Data types 

x = 5 
y = 2.5 
name = "Vivian" #string
is_student = True #type boolean - value true/false 

#Operators +, -, *, // (division), ** (eksponen), % (modulus)

sum = x * y
product = x + y
power = x ** 2 

print(power)
print(product)
print(sum)

25
7.5


In [15]:
# Control Flow
if x > y:
    print(f"{x} is greater than {y}")
else:
     print(f"{x} is less than or equal to {y}")
        
#for Loop 
for i in range(5): 
    print(i) #loop trough angka 0 ke 5 tapi 5 nya gaikut

#while Loop
j = 4
while j<8:
    print(j)
    j += 1 #kalau j udah lebih dari atau sama dengan 5 berarti berhenti print 
print("I am out")

5 is greater than 2.5
0
1
2
3
4
4
5
6
7
I am out


In [17]:
#Function (gabakalan kepakai kalau tidak dipanggil)

def greet(name):
    return f"Helo, {name}"

print(greet("Vivian Aranha"))
    

Helo, Vivian Aranha


In [20]:
# Lists 

numbers = [1, 2, 3, 4, 5]
print(numbers[0]) #0 is the first item on the list dan lanjut selanjutnya 

     # append, remove, pop, slice 
numbers.append(7)
print(numbers)

1
[1, 2, 3, 4, 5, 7]


In [22]:
# Dictionaries 

student = {"name" : "Vivian", "age" : 40, "is_student" : True}
print(student['age'])
print(student['name'])

40
Vivian


In [26]:
# numpy - for numbers 

# Creating Array 
import numpy as np 

array = np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


In [27]:
array2 = np.array([3,4,5,6,7])
print(array + array2)

[ 4  6  8 10 12]


In [31]:
#buat matrix 
matrix = np.array([[1,2],
                  [3,4]])
print(np.dot(matrix,matrix)) #ngasi hasil matrix kali matrix

[[ 7 10]
 [15 22]]


In [1]:
# intro to pandas - use for data manipulation and data structure

#loading and read data
import pandas as pd 

data = pd.read_excel(r"C:\Users\ASUS\Downloads\DataCoba.xlsx")

print(data.head())

      Name  Age         City
0    Alice   18     New York
1      Bob   25  Los Angeles
2  Charlie   19      Chicago
3    David   16      Houston
4      Eve   22      Phoenix


In [3]:
# data manipulation - cuman ngambil bagian yang diminta

name = data['Name']
print(name)

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: Name, dtype: object


In [5]:
filtered_Data = data[data['Age'] > 18]
print(filtered_Data)

      Name  Age         City
1      Bob   25  Los Angeles
2  Charlie   19      Chicago
4      Eve   22      Phoenix


In [6]:
print(data.describe())
#count - ada berapa banyak data 

             Age
count   5.000000
mean   20.000000
std     3.535534
min    16.000000
25%    18.000000
50%    19.000000
75%    22.000000
max    25.000000


In [ ]:
# task 1 

